// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      // apiKey: 'AIzaSyCz_NJ0XyfbpIiiqjA3-ZLs-S9DPG0Ilos',
      // appId: '1:660153904831:web:5a3a358f6f72afae39e00a',
      // messagingSenderId: '660153904831',
      // projectId: 'dupa123-4b1fa',
      // authDomain: 'dupa123-4b1fa.firebaseapp.com',
      // databaseURL: 'https://dupa123-4b1fa-default-rtdb.firebaseio.com',
      // storageBucket: 'dupa123-4b1fa.appspot.com',
      apiKey: "AIzaSyCBJOKG9ts3K0kpSGs1J_P_G5l22zhdniI",
      authDomain: "fs-ankieta-badabada.firebaseapp.com",
      databaseURL:
          "https://fs-ankieta-badabada-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "fs-ankieta-badabada",
      storageBucket: "fs-ankieta-badabada.appspot.com",
      messagingSenderId: "479245572336",
      appId: "1:479245572336:web:11ffb1bcac600d373b8a35",
      measurementId: "G-EY19LLMCXB"
      );
}
